services:
  spring-boot:
    build: .
    ports:
      - 8081:8081
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: 17052002
      MYSQL_PORT: 3306
      MYSQL_DATABASE: socialapp
    depends_on:
      - mysql
  mysql:
    container_name: mysqldb
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 17052002
      MYSQL_DATABASE: socialapp
#     volumes:
#       - ./DataSqlExport.sql:/docker-entrypoint-initdb.d/init.sql